language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
    
before_install:
  # Scripts are set as executable
  - chmod +x ./.scripts/load-travis-environment.sh
  - chmod +x ./.scripts/create-maven-settings.sh
  - chmod +x ./.scripts/deploy.sh
  - chmod +x ./.scripts/deploy-site.sh
  # Prepares CI environment
  - source ./.scripts/load-travis-environment.sh
  # Creates Maven settings
  - ./.scripts/create-maven-settings.sh
script:
  # Unit and integration tests are run
  - mvn clean verify
after_success:
  # Documentation deployment script
  - ./.scripts/deploy-site.sh
  # Code artifacts deployment script
  - ./.scripts/deploy.sh
